title: Shashank Vuppugalla
logo: Shashank_profile_rounded.png
description: I’m a robotics enthusiast with a  background in controls, computer vision, and data science. I enjoy tackling interdisciplinary problems that merge mechanical systems, software engineering, and AI to push the boundaries of what’s possible in robotics. I aim to create innovative, scalable solutions that positively impact industries and everyday life.
show_downloads: False
theme: jekyll-theme-minimal
